<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Destinoturistico', 'doctrine');

/**
 * BaseDestinoturistico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dst_codigo
 * @property string $dst_destino
 * @property Doctrine_Collection $Preferenciaturistica
 * 
 * @method integer             getDstCodigo()            Returns the current record's "dst_codigo" value
 * @method string              getDstDestino()           Returns the current record's "dst_destino" value
 * @method Doctrine_Collection getPreferenciaturistica() Returns the current record's "Preferenciaturistica" collection
 * @method Destinoturistico    setDstCodigo()            Sets the current record's "dst_codigo" value
 * @method Destinoturistico    setDstDestino()           Sets the current record's "dst_destino" value
 * @method Destinoturistico    setPreferenciaturistica() Sets the current record's "Preferenciaturistica" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDestinoturistico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('destinoturistico');
        $this->hasColumn('dst_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('dst_destino', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Preferenciaturistica', array(
             'local' => 'dst_codigo',
             'foreign' => 'prt_dst_codigo'));
    }
}