<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Hotel', 'doctrine');

/**
 * BaseHotel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hot_codigo
 * @property string $hot_nombre
 * @property string $hot_direccion
 * @property string $hot_telefono
 * @property string $hot_web
 * @property string $hot_email
 * @property integer $hot_valor_noche
 * @property Doctrine_Collection $Reservahotel
 * 
 * @method integer             getHotCodigo()       Returns the current record's "hot_codigo" value
 * @method string              getHotNombre()       Returns the current record's "hot_nombre" value
 * @method string              getHotDireccion()    Returns the current record's "hot_direccion" value
 * @method string              getHotTelefono()     Returns the current record's "hot_telefono" value
 * @method string              getHotWeb()          Returns the current record's "hot_web" value
 * @method string              getHotEmail()        Returns the current record's "hot_email" value
 * @method integer             getHotValorNoche()   Returns the current record's "hot_valor_noche" value
 * @method Doctrine_Collection getReservahotel()    Returns the current record's "Reservahotel" collection
 * @method Hotel               setHotCodigo()       Sets the current record's "hot_codigo" value
 * @method Hotel               setHotNombre()       Sets the current record's "hot_nombre" value
 * @method Hotel               setHotDireccion()    Sets the current record's "hot_direccion" value
 * @method Hotel               setHotTelefono()     Sets the current record's "hot_telefono" value
 * @method Hotel               setHotWeb()          Sets the current record's "hot_web" value
 * @method Hotel               setHotEmail()        Sets the current record's "hot_email" value
 * @method Hotel               setHotValorNoche()   Sets the current record's "hot_valor_noche" value
 * @method Hotel               setReservahotel()    Sets the current record's "Reservahotel" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHotel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hotel');
        $this->hasColumn('hot_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('hot_nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('hot_direccion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('hot_telefono', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('hot_web', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('hot_email', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('hot_valor_noche', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Reservahotel', array(
             'local' => 'hot_codigo',
             'foreign' => 'reh_hot_codigo'));
    }
}