<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tratamiento', 'doctrine');

/**
 * BaseTratamiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tra_codigo
 * @property integer $tra_pac_codigo
 * @property date $tra_fecha_partida
 * @property integer $tra_tiempo_estadia
 * @property integer $tra_apto_operacion
 * @property integer $tra_costo_basico
 * @property Paciente $Paciente
 * @property Doctrine_Collection $Dietapaciente
 * @property Doctrine_Collection $Logistica
 * @property Doctrine_Collection $Postoperatorio
 * @property Doctrine_Collection $Preoperatorio
 * @property Doctrine_Collection $Procedimiento
 * @property Doctrine_Collection $Reservahotel
 * @property Doctrine_Collection $Reservavuelo
 * 
 * @method integer             getTraCodigo()          Returns the current record's "tra_codigo" value
 * @method integer             getTraPacCodigo()       Returns the current record's "tra_pac_codigo" value
 * @method date                getTraFechaPartida()    Returns the current record's "tra_fecha_partida" value
 * @method integer             getTraTiempoEstadia()   Returns the current record's "tra_tiempo_estadia" value
 * @method integer             getTraAptoOperacion()   Returns the current record's "tra_apto_operacion" value
 * @method integer             getTraCostoBasico()     Returns the current record's "tra_costo_basico" value
 * @method Paciente            getPaciente()           Returns the current record's "Paciente" value
 * @method Doctrine_Collection getDietapaciente()      Returns the current record's "Dietapaciente" collection
 * @method Doctrine_Collection getLogistica()          Returns the current record's "Logistica" collection
 * @method Doctrine_Collection getPostoperatorio()     Returns the current record's "Postoperatorio" collection
 * @method Doctrine_Collection getPreoperatorio()      Returns the current record's "Preoperatorio" collection
 * @method Doctrine_Collection getProcedimiento()      Returns the current record's "Procedimiento" collection
 * @method Doctrine_Collection getReservahotel()       Returns the current record's "Reservahotel" collection
 * @method Doctrine_Collection getReservavuelo()       Returns the current record's "Reservavuelo" collection
 * @method Tratamiento         setTraCodigo()          Sets the current record's "tra_codigo" value
 * @method Tratamiento         setTraPacCodigo()       Sets the current record's "tra_pac_codigo" value
 * @method Tratamiento         setTraFechaPartida()    Sets the current record's "tra_fecha_partida" value
 * @method Tratamiento         setTraTiempoEstadia()   Sets the current record's "tra_tiempo_estadia" value
 * @method Tratamiento         setTraAptoOperacion()   Sets the current record's "tra_apto_operacion" value
 * @method Tratamiento         setTraCostoBasico()     Sets the current record's "tra_costo_basico" value
 * @method Tratamiento         setPaciente()           Sets the current record's "Paciente" value
 * @method Tratamiento         setDietapaciente()      Sets the current record's "Dietapaciente" collection
 * @method Tratamiento         setLogistica()          Sets the current record's "Logistica" collection
 * @method Tratamiento         setPostoperatorio()     Sets the current record's "Postoperatorio" collection
 * @method Tratamiento         setPreoperatorio()      Sets the current record's "Preoperatorio" collection
 * @method Tratamiento         setProcedimiento()      Sets the current record's "Procedimiento" collection
 * @method Tratamiento         setReservahotel()       Sets the current record's "Reservahotel" collection
 * @method Tratamiento         setReservavuelo()       Sets the current record's "Reservavuelo" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTratamiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tratamiento');
        $this->hasColumn('tra_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('tra_pac_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('tra_fecha_partida', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tra_tiempo_estadia', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('tra_apto_operacion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('tra_costo_basico', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Paciente', array(
             'local' => 'tra_pac_codigo',
             'foreign' => 'pac_codigo'));

        $this->hasMany('Dietapaciente', array(
             'local' => 'tra_codigo',
             'foreign' => 'dtp_tra_codigo'));

        $this->hasMany('Logistica', array(
             'local' => 'tra_codigo',
             'foreign' => 'log_tra_codigo'));

        $this->hasMany('Postoperatorio', array(
             'local' => 'tra_codigo',
             'foreign' => 'pos_tra_codigo'));

        $this->hasMany('Preoperatorio', array(
             'local' => 'tra_codigo',
             'foreign' => 'preo_tra_codigo'));

        $this->hasMany('Procedimiento', array(
             'local' => 'tra_codigo',
             'foreign' => 'pro_tra_codigo'));

        $this->hasMany('Reservahotel', array(
             'local' => 'tra_codigo',
             'foreign' => 'reh_tra_codigo'));

        $this->hasMany('Reservavuelo', array(
             'local' => 'tra_codigo',
             'foreign' => 'vue_tra_codigo'));
    }
}