<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Elementosxintervencion', 'doctrine');

/**
 * BaseElementosxintervencion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $exi_preo_codigo
 * @property integer $exi_maq_codigo
 * @property integer $exi_cantidad
 * @property Preoperatorio $Preoperatorio
 * @property Materialquirurgico $Materialquirurgico
 * 
 * @method integer                getExiPreoCodigo()      Returns the current record's "exi_preo_codigo" value
 * @method integer                getExiMaqCodigo()       Returns the current record's "exi_maq_codigo" value
 * @method integer                getExiCantidad()        Returns the current record's "exi_cantidad" value
 * @method Preoperatorio          getPreoperatorio()      Returns the current record's "Preoperatorio" value
 * @method Materialquirurgico     getMaterialquirurgico() Returns the current record's "Materialquirurgico" value
 * @method Elementosxintervencion setExiPreoCodigo()      Sets the current record's "exi_preo_codigo" value
 * @method Elementosxintervencion setExiMaqCodigo()       Sets the current record's "exi_maq_codigo" value
 * @method Elementosxintervencion setExiCantidad()        Sets the current record's "exi_cantidad" value
 * @method Elementosxintervencion setPreoperatorio()      Sets the current record's "Preoperatorio" value
 * @method Elementosxintervencion setMaterialquirurgico() Sets the current record's "Materialquirurgico" value
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseElementosxintervencion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('elementosxintervencion');
        $this->hasColumn('exi_preo_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('exi_maq_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('exi_cantidad', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Preoperatorio', array(
             'local' => 'exi_preo_codigo',
             'foreign' => 'preo_codigo'));

        $this->hasOne('Materialquirurgico', array(
             'local' => 'exi_maq_codigo',
             'foreign' => 'maq_codigo'));
    }
}