<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Foto', 'doctrine');

/**
 * BaseFoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fot_codigo
 * @property string $fot_nombre
 * @property string $fot_uri_imagen
 * @property integer $fot_preoperatoria
 * @property integer $fot_preo_codigo
 * @property integer $fot_pos_codigo
 * @property Preoperatorio $Preoperatorio
 * @property Postoperatorio $Postoperatorio
 * 
 * @method integer        getFotCodigo()         Returns the current record's "fot_codigo" value
 * @method string         getFotNombre()         Returns the current record's "fot_nombre" value
 * @method string         getFotUriImagen()      Returns the current record's "fot_uri_imagen" value
 * @method integer        getFotPreoperatoria()  Returns the current record's "fot_preoperatoria" value
 * @method integer        getFotPreoCodigo()     Returns the current record's "fot_preo_codigo" value
 * @method integer        getFotPosCodigo()      Returns the current record's "fot_pos_codigo" value
 * @method Preoperatorio  getPreoperatorio()     Returns the current record's "Preoperatorio" value
 * @method Postoperatorio getPostoperatorio()    Returns the current record's "Postoperatorio" value
 * @method Foto           setFotCodigo()         Sets the current record's "fot_codigo" value
 * @method Foto           setFotNombre()         Sets the current record's "fot_nombre" value
 * @method Foto           setFotUriImagen()      Sets the current record's "fot_uri_imagen" value
 * @method Foto           setFotPreoperatoria()  Sets the current record's "fot_preoperatoria" value
 * @method Foto           setFotPreoCodigo()     Sets the current record's "fot_preo_codigo" value
 * @method Foto           setFotPosCodigo()      Sets the current record's "fot_pos_codigo" value
 * @method Foto           setPreoperatorio()     Sets the current record's "Preoperatorio" value
 * @method Foto           setPostoperatorio()    Sets the current record's "Postoperatorio" value
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('foto');
        $this->hasColumn('fot_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('fot_nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('fot_uri_imagen', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('fot_preoperatoria', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('fot_preo_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fot_pos_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Preoperatorio', array(
             'local' => 'fot_preo_codigo',
             'foreign' => 'preo_codigo'));

        $this->hasOne('Postoperatorio', array(
             'local' => 'fot_pos_codigo',
             'foreign' => 'pos_codigo'));
    }
}