<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Paciente', 'doctrine');

/**
 * BasePaciente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pac_codigo
 * @property string $pac_nombre
 * @property string $pac_identificacion
 * @property date $pac_fecha_nacimiento
 * @property string $pac_telefono1
 * @property string $pac_telefono2
 * @property string $pac_email
 * @property string $pac_direccion
 * @property string $pac_ciudad
 * @property string $pac_estado
 * @property string $pac_pais
 * @property integer $pac_cod_postal
 * @property Doctrine_Collection $Contacto
 * @property Doctrine_Collection $Tratamiento
 * @property Doctrine_Collection $Preferenciaturistica
 * 
 * @method integer             getPacCodigo()            Returns the current record's "pac_codigo" value
 * @method string              getPacNombre()            Returns the current record's "pac_nombre" value
 * @method string              getPacIdentificacion()    Returns the current record's "pac_identificacion" value
 * @method date                getPacFechaNacimiento()   Returns the current record's "pac_fecha_nacimiento" value
 * @method string              getPacTelefono1()         Returns the current record's "pac_telefono1" value
 * @method string              getPacTelefono2()         Returns the current record's "pac_telefono2" value
 * @method string              getPacEmail()             Returns the current record's "pac_email" value
 * @method string              getPacDireccion()         Returns the current record's "pac_direccion" value
 * @method string              getPacCiudad()            Returns the current record's "pac_ciudad" value
 * @method string              getPacEstado()            Returns the current record's "pac_estado" value
 * @method string              getPacPais()              Returns the current record's "pac_pais" value
 * @method integer             getPacCodPostal()         Returns the current record's "pac_cod_postal" value
 * @method Doctrine_Collection getContacto()             Returns the current record's "Contacto" collection
 * @method Doctrine_Collection getTratamiento()          Returns the current record's "Tratamiento" collection
 * @method Doctrine_Collection getPreferenciaturistica() Returns the current record's "Preferenciaturistica" collection
 * @method Paciente            setPacCodigo()            Sets the current record's "pac_codigo" value
 * @method Paciente            setPacNombre()            Sets the current record's "pac_nombre" value
 * @method Paciente            setPacIdentificacion()    Sets the current record's "pac_identificacion" value
 * @method Paciente            setPacFechaNacimiento()   Sets the current record's "pac_fecha_nacimiento" value
 * @method Paciente            setPacTelefono1()         Sets the current record's "pac_telefono1" value
 * @method Paciente            setPacTelefono2()         Sets the current record's "pac_telefono2" value
 * @method Paciente            setPacEmail()             Sets the current record's "pac_email" value
 * @method Paciente            setPacDireccion()         Sets the current record's "pac_direccion" value
 * @method Paciente            setPacCiudad()            Sets the current record's "pac_ciudad" value
 * @method Paciente            setPacEstado()            Sets the current record's "pac_estado" value
 * @method Paciente            setPacPais()              Sets the current record's "pac_pais" value
 * @method Paciente            setPacCodPostal()         Sets the current record's "pac_cod_postal" value
 * @method Paciente            setContacto()             Sets the current record's "Contacto" collection
 * @method Paciente            setTratamiento()          Sets the current record's "Tratamiento" collection
 * @method Paciente            setPreferenciaturistica() Sets the current record's "Preferenciaturistica" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaciente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paciente');
        $this->hasColumn('pac_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('pac_nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('pac_identificacion', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('pac_fecha_nacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('pac_telefono1', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('pac_telefono2', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('pac_email', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('pac_direccion', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('pac_ciudad', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('pac_estado', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('pac_pais', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('pac_cod_postal', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contacto', array(
             'local' => 'pac_codigo',
             'foreign' => 'con_pac_codigo'));

        $this->hasMany('Tratamiento', array(
             'local' => 'pac_codigo',
             'foreign' => 'tra_pac_codigo'));

        $this->hasMany('Preferenciaturistica', array(
             'local' => 'pac_codigo',
             'foreign' => 'prt_pac_codigo'));
    }
}