<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Procedimiento', 'doctrine');

/**
 * BaseProcedimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pro_codigo
 * @property integer $pro_tra_codigo
 * @property integer $pro_tit_codigo
 * @property integer $pro_dtr_codigo
 * @property string $pro_otro
 * @property Tratamiento $Tratamiento
 * @property Tipotratamiento $Tipotratamiento
 * @property Descripciontratamiento $Descripciontratamiento
 * 
 * @method integer                getProCodigo()              Returns the current record's "pro_codigo" value
 * @method integer                getProTraCodigo()           Returns the current record's "pro_tra_codigo" value
 * @method integer                getProTitCodigo()           Returns the current record's "pro_tit_codigo" value
 * @method integer                getProDtrCodigo()           Returns the current record's "pro_dtr_codigo" value
 * @method string                 getProOtro()                Returns the current record's "pro_otro" value
 * @method Tratamiento            getTratamiento()            Returns the current record's "Tratamiento" value
 * @method Tipotratamiento        getTipotratamiento()        Returns the current record's "Tipotratamiento" value
 * @method Descripciontratamiento getDescripciontratamiento() Returns the current record's "Descripciontratamiento" value
 * @method Procedimiento          setProCodigo()              Sets the current record's "pro_codigo" value
 * @method Procedimiento          setProTraCodigo()           Sets the current record's "pro_tra_codigo" value
 * @method Procedimiento          setProTitCodigo()           Sets the current record's "pro_tit_codigo" value
 * @method Procedimiento          setProDtrCodigo()           Sets the current record's "pro_dtr_codigo" value
 * @method Procedimiento          setProOtro()                Sets the current record's "pro_otro" value
 * @method Procedimiento          setTratamiento()            Sets the current record's "Tratamiento" value
 * @method Procedimiento          setTipotratamiento()        Sets the current record's "Tipotratamiento" value
 * @method Procedimiento          setDescripciontratamiento() Sets the current record's "Descripciontratamiento" value
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProcedimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('procedimiento');
        $this->hasColumn('pro_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('pro_tra_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('pro_tit_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('pro_dtr_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('pro_otro', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tratamiento', array(
             'local' => 'pro_tra_codigo',
             'foreign' => 'tra_codigo'));

        $this->hasOne('Tipotratamiento', array(
             'local' => 'pro_tit_codigo',
             'foreign' => 'tit_codigo'));

        $this->hasOne('Descripciontratamiento', array(
             'local' => 'pro_dtr_codigo',
             'foreign' => 'dtr_codigo'));
    }
}