<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Contactologistica', 'doctrine');

/**
 * BaseContactologistica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $clo_codigo
 * @property string $clo_nombre
 * @property string $clo_identificacion
 * @property string $clo_telefono
 * @property string $clo_email
 * @property string $clo_direccion
 * @property string $clo_caracteristica
 * @property Doctrine_Collection $Logistica
 * @property Doctrine_Collection $Logistica_3
 * 
 * @method integer             getCloCodigo()          Returns the current record's "clo_codigo" value
 * @method string              getCloNombre()          Returns the current record's "clo_nombre" value
 * @method string              getCloIdentificacion()  Returns the current record's "clo_identificacion" value
 * @method string              getCloTelefono()        Returns the current record's "clo_telefono" value
 * @method string              getCloEmail()           Returns the current record's "clo_email" value
 * @method string              getCloDireccion()       Returns the current record's "clo_direccion" value
 * @method string              getCloCaracteristica()  Returns the current record's "clo_caracteristica" value
 * @method Doctrine_Collection getLogistica()          Returns the current record's "Logistica" collection
 * @method Doctrine_Collection getLogistica3()         Returns the current record's "Logistica_3" collection
 * @method Contactologistica   setCloCodigo()          Sets the current record's "clo_codigo" value
 * @method Contactologistica   setCloNombre()          Sets the current record's "clo_nombre" value
 * @method Contactologistica   setCloIdentificacion()  Sets the current record's "clo_identificacion" value
 * @method Contactologistica   setCloTelefono()        Sets the current record's "clo_telefono" value
 * @method Contactologistica   setCloEmail()           Sets the current record's "clo_email" value
 * @method Contactologistica   setCloDireccion()       Sets the current record's "clo_direccion" value
 * @method Contactologistica   setCloCaracteristica()  Sets the current record's "clo_caracteristica" value
 * @method Contactologistica   setLogistica()          Sets the current record's "Logistica" collection
 * @method Contactologistica   setLogistica3()         Sets the current record's "Logistica_3" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContactologistica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactologistica');
        $this->hasColumn('clo_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('clo_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('clo_identificacion', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('clo_telefono', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('clo_email', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('clo_direccion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('clo_caracteristica', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Logistica', array(
             'local' => 'clo_codigo',
             'foreign' => 'log_clo_codigo_responsable'));

        $this->hasMany('Logistica as Logistica_3', array(
             'local' => 'clo_codigo',
             'foreign' => 'log_clo_codigo_guia'));
    }
}