<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Altapostoperatoria', 'doctrine');

/**
 * BaseAltapostoperatoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $apo_codigo
 * @property integer $apo_tra_codigo
 * @property integer $apo_med_codigo
 * @property integer $apo_cli_codigo
 * @property string $apo_exploracion
 * @property string $apo_info_especialista
 * @property string $apo_tratamiento
 * @property string $apo_observaciones
 * @property Clinica $Clinica
 * 
 * @method integer            getApoCodigo()             Returns the current record's "apo_codigo" value
 * @method integer            getApoTraCodigo()          Returns the current record's "apo_tra_codigo" value
 * @method integer            getApoMedCodigo()          Returns the current record's "apo_med_codigo" value
 * @method integer            getApoCliCodigo()          Returns the current record's "apo_cli_codigo" value
 * @method string             getApoExploracion()        Returns the current record's "apo_exploracion" value
 * @method string             getApoInfoEspecialista()   Returns the current record's "apo_info_especialista" value
 * @method string             getApoTratamiento()        Returns the current record's "apo_tratamiento" value
 * @method string             getApoObservaciones()      Returns the current record's "apo_observaciones" value
 * @method Clinica            getClinica()               Returns the current record's "Clinica" value
 * @method Altapostoperatoria setApoCodigo()             Sets the current record's "apo_codigo" value
 * @method Altapostoperatoria setApoTraCodigo()          Sets the current record's "apo_tra_codigo" value
 * @method Altapostoperatoria setApoMedCodigo()          Sets the current record's "apo_med_codigo" value
 * @method Altapostoperatoria setApoCliCodigo()          Sets the current record's "apo_cli_codigo" value
 * @method Altapostoperatoria setApoExploracion()        Sets the current record's "apo_exploracion" value
 * @method Altapostoperatoria setApoInfoEspecialista()   Sets the current record's "apo_info_especialista" value
 * @method Altapostoperatoria setApoTratamiento()        Sets the current record's "apo_tratamiento" value
 * @method Altapostoperatoria setApoObservaciones()      Sets the current record's "apo_observaciones" value
 * @method Altapostoperatoria setClinica()               Sets the current record's "Clinica" value
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAltapostoperatoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('altapostoperatoria');
        $this->hasColumn('apo_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('apo_tra_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('apo_med_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('apo_cli_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('apo_exploracion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('apo_info_especialista', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('apo_tratamiento', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('apo_observaciones', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Clinica', array(
             'local' => 'apo_cli_codigo',
             'foreign' => 'cli_codigo'));
    }
}