<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Preferenciaturistica', 'doctrine');

/**
 * BasePreferenciaturistica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $prt_pac_codigo
 * @property integer $prt_dst_codigo
 * @property Paciente $Paciente
 * @property Destinoturistico $Destinoturistico
 * 
 * @method integer              getPrtPacCodigo()     Returns the current record's "prt_pac_codigo" value
 * @method integer              getPrtDstCodigo()     Returns the current record's "prt_dst_codigo" value
 * @method Paciente             getPaciente()         Returns the current record's "Paciente" value
 * @method Destinoturistico     getDestinoturistico() Returns the current record's "Destinoturistico" value
 * @method Preferenciaturistica setPrtPacCodigo()     Sets the current record's "prt_pac_codigo" value
 * @method Preferenciaturistica setPrtDstCodigo()     Sets the current record's "prt_dst_codigo" value
 * @method Preferenciaturistica setPaciente()         Sets the current record's "Paciente" value
 * @method Preferenciaturistica setDestinoturistico() Sets the current record's "Destinoturistico" value
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePreferenciaturistica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('preferenciaturistica');
        $this->hasColumn('prt_pac_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('prt_dst_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Paciente', array(
             'local' => 'prt_pac_codigo',
             'foreign' => 'pac_codigo'));

        $this->hasOne('Destinoturistico', array(
             'local' => 'prt_dst_codigo',
             'foreign' => 'dst_codigo'));
    }
}