<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Menu', 'doctrine');

/**
 * BaseMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $men_codigo
 * @property string $men_desayuno
 * @property string $men_almuerzo
 * @property string $men_comida
 * @property integer $men_dtp_codigo
 * @property Dietapaciente $Dietapaciente
 * 
 * @method integer       getMenCodigo()      Returns the current record's "men_codigo" value
 * @method string        getMenDesayuno()    Returns the current record's "men_desayuno" value
 * @method string        getMenAlmuerzo()    Returns the current record's "men_almuerzo" value
 * @method string        getMenComida()      Returns the current record's "men_comida" value
 * @method integer       getMenDtpCodigo()   Returns the current record's "men_dtp_codigo" value
 * @method Dietapaciente getDietapaciente()  Returns the current record's "Dietapaciente" value
 * @method Menu          setMenCodigo()      Sets the current record's "men_codigo" value
 * @method Menu          setMenDesayuno()    Sets the current record's "men_desayuno" value
 * @method Menu          setMenAlmuerzo()    Sets the current record's "men_almuerzo" value
 * @method Menu          setMenComida()      Sets the current record's "men_comida" value
 * @method Menu          setMenDtpCodigo()   Sets the current record's "men_dtp_codigo" value
 * @method Menu          setDietapaciente()  Sets the current record's "Dietapaciente" value
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu');
        $this->hasColumn('men_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('men_desayuno', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('men_almuerzo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('men_comida', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('men_dtp_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dietapaciente', array(
             'local' => 'men_dtp_codigo',
             'foreign' => 'dtp_codigo'));
    }
}