<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Enfermera', 'doctrine');

/**
 * BaseEnfermera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $enf_codigo
 * @property string $enf_nombre
 * @property integer $enf_valor_servicio
 * @property Doctrine_Collection $Postoperatorio
 * @property Doctrine_Collection $Preoperatorio
 * 
 * @method integer             getEnfCodigo()          Returns the current record's "enf_codigo" value
 * @method string              getEnfNombre()          Returns the current record's "enf_nombre" value
 * @method integer             getEnfValorServicio()   Returns the current record's "enf_valor_servicio" value
 * @method Doctrine_Collection getPostoperatorio()     Returns the current record's "Postoperatorio" collection
 * @method Doctrine_Collection getPreoperatorio()      Returns the current record's "Preoperatorio" collection
 * @method Enfermera           setEnfCodigo()          Sets the current record's "enf_codigo" value
 * @method Enfermera           setEnfNombre()          Sets the current record's "enf_nombre" value
 * @method Enfermera           setEnfValorServicio()   Sets the current record's "enf_valor_servicio" value
 * @method Enfermera           setPostoperatorio()     Sets the current record's "Postoperatorio" collection
 * @method Enfermera           setPreoperatorio()      Sets the current record's "Preoperatorio" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEnfermera extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('enfermera');
        $this->hasColumn('enf_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('enf_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('enf_valor_servicio', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Postoperatorio', array(
             'local' => 'enf_codigo',
             'foreign' => 'pos_enf_codigo'));

        $this->hasMany('Preoperatorio', array(
             'local' => 'enf_codigo',
             'foreign' => 'preo_enf_codigo'));
    }
}