<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Descripciontratamiento', 'doctrine');

/**
 * BaseDescripciontratamiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dtr_codigo
 * @property integer $dtr_tit_codigo
 * @property string $dtr_descripcion
 * @property Doctrine_Collection $Procedimiento
 * @property Tipotratamiento $Tipotratamiento
 * 
 * @method integer                getDtrCodigo()       Returns the current record's "dtr_codigo" value
 * @method integer                getDtrTitCodigo()    Returns the current record's "dtr_tit_codigo" value
 * @method string                 getDtrDescripcion()  Returns the current record's "dtr_descripcion" value
 * @method Doctrine_Collection    getProcedimiento()   Returns the current record's "Procedimiento" collection
 * @method Tipotratamiento        getTipotratamiento() Returns the current record's "Tipotratamiento" value
 * @method Descripciontratamiento setDtrCodigo()       Sets the current record's "dtr_codigo" value
 * @method Descripciontratamiento setDtrTitCodigo()    Sets the current record's "dtr_tit_codigo" value
 * @method Descripciontratamiento setDtrDescripcion()  Sets the current record's "dtr_descripcion" value
 * @method Descripciontratamiento setProcedimiento()   Sets the current record's "Procedimiento" collection
 * @method Descripciontratamiento setTipotratamiento() Sets the current record's "Tipotratamiento" value
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDescripciontratamiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('descripciontratamiento');
        $this->hasColumn('dtr_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('dtr_tit_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('dtr_descripcion', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Procedimiento', array(
             'local' => 'dtr_codigo',
             'foreign' => 'pro_dtr_codigo'));

        $this->hasOne('Tipotratamiento', array(
             'local' => 'dtr_tit_codigo',
             'foreign' => 'tit_codigo'));
    }
}