<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Clinica', 'doctrine');

/**
 * BaseClinica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cli_codigo
 * @property string $cli_nombre
 * @property string $cli_direccion
 * @property string $cli_telefono
 * @property Doctrine_Collection $Altapostoperatoria
 * @property Doctrine_Collection $Preoperatorio
 * 
 * @method integer             getCliCodigo()          Returns the current record's "cli_codigo" value
 * @method string              getCliNombre()          Returns the current record's "cli_nombre" value
 * @method string              getCliDireccion()       Returns the current record's "cli_direccion" value
 * @method string              getCliTelefono()        Returns the current record's "cli_telefono" value
 * @method Doctrine_Collection getAltapostoperatoria() Returns the current record's "Altapostoperatoria" collection
 * @method Doctrine_Collection getPreoperatorio()      Returns the current record's "Preoperatorio" collection
 * @method Clinica             setCliCodigo()          Sets the current record's "cli_codigo" value
 * @method Clinica             setCliNombre()          Sets the current record's "cli_nombre" value
 * @method Clinica             setCliDireccion()       Sets the current record's "cli_direccion" value
 * @method Clinica             setCliTelefono()        Sets the current record's "cli_telefono" value
 * @method Clinica             setAltapostoperatoria() Sets the current record's "Altapostoperatoria" collection
 * @method Clinica             setPreoperatorio()      Sets the current record's "Preoperatorio" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClinica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clinica');
        $this->hasColumn('cli_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('cli_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('cli_direccion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('cli_telefono', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Altapostoperatoria', array(
             'local' => 'cli_codigo',
             'foreign' => 'apo_cli_codigo'));

        $this->hasMany('Preoperatorio', array(
             'local' => 'cli_codigo',
             'foreign' => 'preo_cli_codigo'));
    }
}