<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tipotratamiento', 'doctrine');

/**
 * BaseTipotratamiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tit_codigo
 * @property string $tit_nombre
 * @property Doctrine_Collection $Procedimiento
 * @property Doctrine_Collection $Descripciontratamiento
 * 
 * @method integer             getTitCodigo()              Returns the current record's "tit_codigo" value
 * @method string              getTitNombre()              Returns the current record's "tit_nombre" value
 * @method Doctrine_Collection getProcedimiento()          Returns the current record's "Procedimiento" collection
 * @method Doctrine_Collection getDescripciontratamiento() Returns the current record's "Descripciontratamiento" collection
 * @method Tipotratamiento     setTitCodigo()              Sets the current record's "tit_codigo" value
 * @method Tipotratamiento     setTitNombre()              Sets the current record's "tit_nombre" value
 * @method Tipotratamiento     setProcedimiento()          Sets the current record's "Procedimiento" collection
 * @method Tipotratamiento     setDescripciontratamiento() Sets the current record's "Descripciontratamiento" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipotratamiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipotratamiento');
        $this->hasColumn('tit_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('tit_nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Otro',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Procedimiento', array(
             'local' => 'tit_codigo',
             'foreign' => 'pro_tit_codigo'));

        $this->hasMany('Descripciontratamiento', array(
             'local' => 'tit_codigo',
             'foreign' => 'dtr_tit_codigo'));
    }
}