<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Logistica', 'doctrine');

/**
 * BaseLogistica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $log_codigo
 * @property integer $log_tra_codigo
 * @property integer $log_reh_codigo
 * @property integer $log_vue_codigo
 * @property integer $log_trans_codigo
 * @property integer $log_clo_codigo_responsable
 * @property integer $log_clo_codigo_guia
 * @property string $log_observaciones
 * @property string $log_observaciones_transporte
 * @property Tratamiento $Tratamiento
 * @property Contactologistica $Contactologistica
 * @property Contactologistica $Contactologistica_3
 * @property Reservahotel $Reservahotel
 * @property Reservavuelo $Reservavuelo
 * @property Transporte $Transporte
 * 
 * @method integer           getLogCodigo()                    Returns the current record's "log_codigo" value
 * @method integer           getLogTraCodigo()                 Returns the current record's "log_tra_codigo" value
 * @method integer           getLogRehCodigo()                 Returns the current record's "log_reh_codigo" value
 * @method integer           getLogVueCodigo()                 Returns the current record's "log_vue_codigo" value
 * @method integer           getLogTransCodigo()               Returns the current record's "log_trans_codigo" value
 * @method integer           getLogCloCodigoResponsable()      Returns the current record's "log_clo_codigo_responsable" value
 * @method integer           getLogCloCodigoGuia()             Returns the current record's "log_clo_codigo_guia" value
 * @method string            getLogObservaciones()             Returns the current record's "log_observaciones" value
 * @method string            getLogObservacionesTransporte()   Returns the current record's "log_observaciones_transporte" value
 * @method Tratamiento       getTratamiento()                  Returns the current record's "Tratamiento" value
 * @method Contactologistica getContactologistica()            Returns the current record's "Contactologistica" value
 * @method Contactologistica getContactologistica3()           Returns the current record's "Contactologistica_3" value
 * @method Reservahotel      getReservahotel()                 Returns the current record's "Reservahotel" value
 * @method Reservavuelo      getReservavuelo()                 Returns the current record's "Reservavuelo" value
 * @method Transporte        getTransporte()                   Returns the current record's "Transporte" value
 * @method Logistica         setLogCodigo()                    Sets the current record's "log_codigo" value
 * @method Logistica         setLogTraCodigo()                 Sets the current record's "log_tra_codigo" value
 * @method Logistica         setLogRehCodigo()                 Sets the current record's "log_reh_codigo" value
 * @method Logistica         setLogVueCodigo()                 Sets the current record's "log_vue_codigo" value
 * @method Logistica         setLogTransCodigo()               Sets the current record's "log_trans_codigo" value
 * @method Logistica         setLogCloCodigoResponsable()      Sets the current record's "log_clo_codigo_responsable" value
 * @method Logistica         setLogCloCodigoGuia()             Sets the current record's "log_clo_codigo_guia" value
 * @method Logistica         setLogObservaciones()             Sets the current record's "log_observaciones" value
 * @method Logistica         setLogObservacionesTransporte()   Sets the current record's "log_observaciones_transporte" value
 * @method Logistica         setTratamiento()                  Sets the current record's "Tratamiento" value
 * @method Logistica         setContactologistica()            Sets the current record's "Contactologistica" value
 * @method Logistica         setContactologistica3()           Sets the current record's "Contactologistica_3" value
 * @method Logistica         setReservahotel()                 Sets the current record's "Reservahotel" value
 * @method Logistica         setReservavuelo()                 Sets the current record's "Reservavuelo" value
 * @method Logistica         setTransporte()                   Sets the current record's "Transporte" value
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogistica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('logistica');
        $this->hasColumn('log_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('log_tra_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('log_reh_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('log_vue_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('log_trans_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('log_clo_codigo_responsable', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('log_clo_codigo_guia', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('log_observaciones', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('log_observaciones_transporte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tratamiento', array(
             'local' => 'log_tra_codigo',
             'foreign' => 'tra_codigo'));

        $this->hasOne('Contactologistica', array(
             'local' => 'log_clo_codigo_responsable',
             'foreign' => 'clo_codigo'));

        $this->hasOne('Contactologistica as Contactologistica_3', array(
             'local' => 'log_clo_codigo_guia',
             'foreign' => 'clo_codigo'));

        $this->hasOne('Reservahotel', array(
             'local' => 'log_reh_codigo',
             'foreign' => 'reh_codigo'));

        $this->hasOne('Reservavuelo', array(
             'local' => 'log_vue_codigo',
             'foreign' => 'vue_codigo'));

        $this->hasOne('Transporte', array(
             'local' => 'log_trans_codigo',
             'foreign' => 'trans_codigo'));
    }
}