<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Materialquirurgico', 'doctrine');

/**
 * BaseMaterialquirurgico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $maq_codigo
 * @property string $maq_nombre
 * @property integer $maq_valor
 * @property Doctrine_Collection $Elementosxintervencion
 * 
 * @method integer             getMaqCodigo()              Returns the current record's "maq_codigo" value
 * @method string              getMaqNombre()              Returns the current record's "maq_nombre" value
 * @method integer             getMaqValor()               Returns the current record's "maq_valor" value
 * @method Doctrine_Collection getElementosxintervencion() Returns the current record's "Elementosxintervencion" collection
 * @method Materialquirurgico  setMaqCodigo()              Sets the current record's "maq_codigo" value
 * @method Materialquirurgico  setMaqNombre()              Sets the current record's "maq_nombre" value
 * @method Materialquirurgico  setMaqValor()               Sets the current record's "maq_valor" value
 * @method Materialquirurgico  setElementosxintervencion() Sets the current record's "Elementosxintervencion" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMaterialquirurgico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('materialquirurgico');
        $this->hasColumn('maq_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('maq_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('maq_valor', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Elementosxintervencion', array(
             'local' => 'maq_codigo',
             'foreign' => 'exi_maq_codigo'));
    }
}