<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Transporte', 'doctrine');

/**
 * BaseTransporte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $trans_codigo
 * @property string $trans_nombre
 * @property string $trans_identificacion
 * @property string $trans_telefono1
 * @property string $trans_telefono2
 * @property string $trans_direccion
 * @property string $trans_placa_vehiculo
 * @property string $trans_tipo_vehiculo
 * @property string $trans_nombre_companhia
 * @property string $trans_numero_companhia
 * @property string $trans_telefono_companhia
 * @property Doctrine_Collection $Logistica
 * 
 * @method integer             getTransCodigo()              Returns the current record's "trans_codigo" value
 * @method string              getTransNombre()              Returns the current record's "trans_nombre" value
 * @method string              getTransIdentificacion()      Returns the current record's "trans_identificacion" value
 * @method string              getTransTelefono1()           Returns the current record's "trans_telefono1" value
 * @method string              getTransTelefono2()           Returns the current record's "trans_telefono2" value
 * @method string              getTransDireccion()           Returns the current record's "trans_direccion" value
 * @method string              getTransPlacaVehiculo()       Returns the current record's "trans_placa_vehiculo" value
 * @method string              getTransTipoVehiculo()        Returns the current record's "trans_tipo_vehiculo" value
 * @method string              getTransNombreCompanhia()     Returns the current record's "trans_nombre_companhia" value
 * @method string              getTransNumeroCompanhia()     Returns the current record's "trans_numero_companhia" value
 * @method string              getTransTelefonoCompanhia()   Returns the current record's "trans_telefono_companhia" value
 * @method Doctrine_Collection getLogistica()                Returns the current record's "Logistica" collection
 * @method Transporte          setTransCodigo()              Sets the current record's "trans_codigo" value
 * @method Transporte          setTransNombre()              Sets the current record's "trans_nombre" value
 * @method Transporte          setTransIdentificacion()      Sets the current record's "trans_identificacion" value
 * @method Transporte          setTransTelefono1()           Sets the current record's "trans_telefono1" value
 * @method Transporte          setTransTelefono2()           Sets the current record's "trans_telefono2" value
 * @method Transporte          setTransDireccion()           Sets the current record's "trans_direccion" value
 * @method Transporte          setTransPlacaVehiculo()       Sets the current record's "trans_placa_vehiculo" value
 * @method Transporte          setTransTipoVehiculo()        Sets the current record's "trans_tipo_vehiculo" value
 * @method Transporte          setTransNombreCompanhia()     Sets the current record's "trans_nombre_companhia" value
 * @method Transporte          setTransNumeroCompanhia()     Sets the current record's "trans_numero_companhia" value
 * @method Transporte          setTransTelefonoCompanhia()   Sets the current record's "trans_telefono_companhia" value
 * @method Transporte          setLogistica()                Sets the current record's "Logistica" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTransporte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transporte');
        $this->hasColumn('trans_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('trans_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('trans_identificacion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('trans_telefono1', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('trans_telefono2', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('trans_direccion', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('trans_placa_vehiculo', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('trans_tipo_vehiculo', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('trans_nombre_companhia', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('trans_numero_companhia', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('trans_telefono_companhia', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Logistica', array(
             'local' => 'trans_codigo',
             'foreign' => 'log_trans_codigo'));
    }
}