<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Reservavuelo', 'doctrine');

/**
 * BaseReservavuelo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vue_codigo
 * @property integer $vue_tra_codigo
 * @property string $vue_origen
 * @property string $vue_destino
 * @property date $vue_fecha_ida
 * @property date $vue_fecha_regreso
 * @property integer $vue_nro_vuelo_ida
 * @property integer $vue_nro_vuelo_regreso
 * @property time $vue_hora_salida_ida
 * @property time $vue_hora_llegada_ida
 * @property time $vue_hora_salida_vuelta
 * @property time $vue_hora_llegada_vuelta
 * @property integer $vue_valor
 * @property Tratamiento $Tratamiento
 * @property Doctrine_Collection $Logistica
 * 
 * @method integer             getVueCodigo()               Returns the current record's "vue_codigo" value
 * @method integer             getVueTraCodigo()            Returns the current record's "vue_tra_codigo" value
 * @method string              getVueOrigen()               Returns the current record's "vue_origen" value
 * @method string              getVueDestino()              Returns the current record's "vue_destino" value
 * @method date                getVueFechaIda()             Returns the current record's "vue_fecha_ida" value
 * @method date                getVueFechaRegreso()         Returns the current record's "vue_fecha_regreso" value
 * @method integer             getVueNroVueloIda()          Returns the current record's "vue_nro_vuelo_ida" value
 * @method integer             getVueNroVueloRegreso()      Returns the current record's "vue_nro_vuelo_regreso" value
 * @method time                getVueHoraSalidaIda()        Returns the current record's "vue_hora_salida_ida" value
 * @method time                getVueHoraLlegadaIda()       Returns the current record's "vue_hora_llegada_ida" value
 * @method time                getVueHoraSalidaVuelta()     Returns the current record's "vue_hora_salida_vuelta" value
 * @method time                getVueHoraLlegadaVuelta()    Returns the current record's "vue_hora_llegada_vuelta" value
 * @method integer             getVueValor()                Returns the current record's "vue_valor" value
 * @method Tratamiento         getTratamiento()             Returns the current record's "Tratamiento" value
 * @method Doctrine_Collection getLogistica()               Returns the current record's "Logistica" collection
 * @method Reservavuelo        setVueCodigo()               Sets the current record's "vue_codigo" value
 * @method Reservavuelo        setVueTraCodigo()            Sets the current record's "vue_tra_codigo" value
 * @method Reservavuelo        setVueOrigen()               Sets the current record's "vue_origen" value
 * @method Reservavuelo        setVueDestino()              Sets the current record's "vue_destino" value
 * @method Reservavuelo        setVueFechaIda()             Sets the current record's "vue_fecha_ida" value
 * @method Reservavuelo        setVueFechaRegreso()         Sets the current record's "vue_fecha_regreso" value
 * @method Reservavuelo        setVueNroVueloIda()          Sets the current record's "vue_nro_vuelo_ida" value
 * @method Reservavuelo        setVueNroVueloRegreso()      Sets the current record's "vue_nro_vuelo_regreso" value
 * @method Reservavuelo        setVueHoraSalidaIda()        Sets the current record's "vue_hora_salida_ida" value
 * @method Reservavuelo        setVueHoraLlegadaIda()       Sets the current record's "vue_hora_llegada_ida" value
 * @method Reservavuelo        setVueHoraSalidaVuelta()     Sets the current record's "vue_hora_salida_vuelta" value
 * @method Reservavuelo        setVueHoraLlegadaVuelta()    Sets the current record's "vue_hora_llegada_vuelta" value
 * @method Reservavuelo        setVueValor()                Sets the current record's "vue_valor" value
 * @method Reservavuelo        setTratamiento()             Sets the current record's "Tratamiento" value
 * @method Reservavuelo        setLogistica()               Sets the current record's "Logistica" collection
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReservavuelo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reservavuelo');
        $this->hasColumn('vue_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('vue_tra_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('vue_origen', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('vue_destino', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('vue_fecha_ida', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('vue_fecha_regreso', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('vue_nro_vuelo_ida', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('vue_nro_vuelo_regreso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('vue_hora_salida_ida', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('vue_hora_llegada_ida', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('vue_hora_salida_vuelta', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('vue_hora_llegada_vuelta', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('vue_valor', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tratamiento', array(
             'local' => 'vue_tra_codigo',
             'foreign' => 'tra_codigo'));

        $this->hasMany('Logistica', array(
             'local' => 'vue_codigo',
             'foreign' => 'log_vue_codigo'));
    }
}