<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Contacto', 'doctrine');

/**
 * BaseContacto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $con_codigo
 * @property integer $con_pac_codigo
 * @property string $con_nombre
 * @property string $con_telefono1
 * @property string $con_telefono2
 * @property string $con_email
 * @property string $con_direccion
 * @property Paciente $Paciente
 * 
 * @method integer  getConCodigo()      Returns the current record's "con_codigo" value
 * @method integer  getConPacCodigo()   Returns the current record's "con_pac_codigo" value
 * @method string   getConNombre()      Returns the current record's "con_nombre" value
 * @method string   getConTelefono1()   Returns the current record's "con_telefono1" value
 * @method string   getConTelefono2()   Returns the current record's "con_telefono2" value
 * @method string   getConEmail()       Returns the current record's "con_email" value
 * @method string   getConDireccion()   Returns the current record's "con_direccion" value
 * @method Paciente getPaciente()       Returns the current record's "Paciente" value
 * @method Contacto setConCodigo()      Sets the current record's "con_codigo" value
 * @method Contacto setConPacCodigo()   Sets the current record's "con_pac_codigo" value
 * @method Contacto setConNombre()      Sets the current record's "con_nombre" value
 * @method Contacto setConTelefono1()   Sets the current record's "con_telefono1" value
 * @method Contacto setConTelefono2()   Sets the current record's "con_telefono2" value
 * @method Contacto setConEmail()       Sets the current record's "con_email" value
 * @method Contacto setConDireccion()   Sets the current record's "con_direccion" value
 * @method Contacto setPaciente()       Sets the current record's "Paciente" value
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContacto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacto');
        $this->hasColumn('con_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('con_pac_codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('con_nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('con_telefono1', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('con_telefono2', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('con_email', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('con_direccion', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Paciente', array(
             'local' => 'con_pac_codigo',
             'foreign' => 'pac_codigo'));
    }
}