# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  .settings:
    enabled_modules: [default, sfGuardAuth]    
    especialidades: [Cirujano, Odontólogo, Traumatólogo]
    correo_pite: shadow_rev@yahoo.com
    correo_william: willamurillo@gmail.com
    correo_gonzalo: gonzalofuentes@eurobelleza.es
    locale: [en-US, es-ES]

  .mensajes:
    error_validacion: Compruebe los datos obligatorios e intentelo nuevamente
    error_paciente_seleccionado: Primero debe seleccionar un paciente
    guardado_exitoso_m: ha sido guardado exitosamente
    guardado_exitoso_f: ha sido guardada exitosamente
    guardado_exitoso_ms: han sido guardados exitosamente
    guardado_exitoso_fs: han sido guardadas exitosamente
