# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  .settings:
    enabled_modules: [default, sfGuardAuth]    
    especialidades: [Cirujano, Odontólogo, Traumatólogo]
    correo_pite: grupocgb@gmail.com
    #correo_admin: raul.villamarin@correounivalle.edu.co
    correo_medico_adm_1: willamurillo@gmail.com
    correo_medico_adm_2: gonzalofuentes@eurobelleza.es
    locale: [es-ES, en_US]

  .mensajes:
    error_validacion: Compruebe los datos obligatorios e intentelo nuevamente
    error_paciente_seleccionado: Primero debe seleccionar un paciente
    error_paciente_no_valorado: Este paciente no ha sido valorado
    guardado_exitoso_m: ha sido guardado exitosamente
    guardado_exitoso_f: ha sido guardada exitosamente
    guardado_exitoso_ms: han sido guardados exitosamente
    guardado_exitoso_fs: han sido guardadas exitosamente
