<?php

/**
 * Agencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Agencia extends BaseAgencia
{
    public function  __toString() {
        return $this->agn_nombre;
    }
}
