<?php

/**
 * AltapostoperatoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AltapostoperatoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AltapostoperatoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Altapostoperatoria');
    }

    public function buscarPorTratamiento($id_tratamiento)
    {
        $consulta = $this->createQuery()->where('apo_tra_codigo = ' . $id_tratamiento);
        return $consulta->execute()->getFirst();
    }
}