<?php

/**
 * ClinicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClinicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClinicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clinica');
    }
}