<?php

/**
 * ContactologisticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactologisticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactologisticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contactologistica');
    }
}