<?php

/**
 * DietapacienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DietapacienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DietapacienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dietapaciente');
    }
}