<?php

/**
 * ElementosxintervencionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElementosxintervencionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElementosxintervencionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Elementosxintervencion');
    }
}