<?php

/**
 * HotelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HotelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HotelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Hotel');
    }
}