<?php

/**
 * MedicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medico');
    }
}