<?php

/**
 * MedicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medico');
    }

    public function obtenerMedicoPorIdUsuario($id_usuario)
    {
        $consulta = $this->createQuery()->where('med_sfg_id=' . $id_usuario);
        return $consulta->execute()->getFirst();
    }
}