<?php

/**
 * PacienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Paciente');
    }


    public function obtenerPacientesActivos($params = null)
    {
        $consulta = $this->createQuery('p');
        if(!empty($params))
        {
            foreach($params as $parametro=>$valor_parametro)
            {
                if(is_numeric($valor_parametro))
                    $consulta->where('p.' . $parametro . ' = ?', $valor_parametro);
                else
                    $consulta->where('p.' . $parametro . ' LIKE %' . $valor_parametro . '%');
            }
        }

        return $consulta->execute();
    }
}