<?php

/**
 * ReservavueloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservavueloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReservavueloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reservavuelo');
    }

    public function buscarPorTratamiento($codigo_tratamiento)
    {
        $consulta = $this->createQuery('rv')->where('vue_tra_codigo=' . $codigo_tratamiento);
        //return $consulta->execute();
        return $consulta->fetchOne();
    }
}