<?php

/**
 * ReservahotelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservahotelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReservahotelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reservahotel');
    }

    public function buscarPorTratamiento($codigo_tratamiento)
    {
        $consulta = $this->createQuery('rh')->where('reh_tra_codigo=' . $codigo_tratamiento);
        //return $consulta->execute();
        return $consulta->fetchOne();
    }
}