<?php

/**
 * TipotratamientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipotratamientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipotratamientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipotratamiento');
    }
}