<?php

/**
 * TratamientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TratamientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TratamientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tratamiento');
    }
}