generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Clinica
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          clinica
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Cl&iacute;nicas en el Sistema
        display: [=cli_nombre, cli_direccion, cli_telefono]
        fields:
          cli_nombre: {label: Nombre}
          cli_direccion: {label: Direcci&oacute;n}
          cli_telefono: {label: Tel&eacute;fono}
      filter:
        class: false
      form:    ~
      edit:
        title: Actualizando la informaci&oacute;n para %%cli_nombre%%
      new:
        title: Ingresando nueva Cl&iacute;nica
