generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Enfermera
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          enfermera
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Enfermeras registradas en el sistema
        display: [enf_nombre, enf_valor_servicio]
        fields:
          enf_nombre: {label: Nombre}
          enf_valor_servicio: {label: Costo del Servicio}
      filter:
        class: false
      form:    ~
      edit:
        title: Actualizando la informaci&oacute;n de %%enf_nombre%%
      new:
        title: Ingresando un(a) nuevo(a) Enfermero(a)
