<?php

/**
 * AgenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Agencia');
    }
}