<?php

/**
 * DescripciontratamientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DescripciontratamientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DescripciontratamientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Descripciontratamiento');
    }

    public function getQueryListaDescripciones($id_tipo_tratamiento)
    {
        return $this->createQuery('d')->where('d.dtr_tit_codigo = ' . $id_tipo_tratamiento);
    }

    public function getListaDescripciones($id_tipo_tratamiento)
    {
        return $this->getQueryListaDescripciones($id_tipo_tratamiento)->execute();
    }
}