<?php

/**
 * EnfermeraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnfermeraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnfermeraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Enfermera');
    }
}