<?php

/**
 * LogisticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogisticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogisticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Logistica');
    }
}