<?php

/**
 * LogisticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogisticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogisticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Logistica');
    }

    public function obtenerLogisticaTratamiento($id_tratamiento)
    {
        $consulta = $this->createQuery()->where('log_tra_codigo = ' . $id_tratamiento);
        return $consulta->execute()->getFirst();
    }
}