<?php

/**
 * MaterialquirurgicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialquirurgicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialquirurgicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Materialquirurgico');
    }
}