<?php

/**
 * Paciente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Paciente extends BasePaciente
{
    public function getTratamiento()
    {
        $tabla_tratamientos = Doctrine_Core::getTable('Tratamiento');
        $query = $tabla_tratamientos->createQuery('t')->where('tra_pac_codigo=' . $this->pac_codigo)->addOrderBy('tra_codigo');
        return $query->execute();
    }

    public function delete(Doctrine_Connection $conn = null) {
        if(0 < sizeof($this->Contacto))
            $this->Contacto->delete();

        if(0 < sizeof($this->Preferenciaturistica))
            $this->Preferenciaturistica->delete();

        if(0 < sizeof($this->Tratamiento))
            $this->Tratamiento->delete();

        parent::delete($conn);
    }
}
