<?php

/**
 * PostoperatorioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostoperatorioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostoperatorioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Postoperatorio');
    }

    public function obtenerPorTratamiento($id_tratamiento)
    {
        $consulta = $this->createQuery()->where('pos_tra_codigo = ' . $id_tratamiento);
        return $consulta->execute()->getFirst();
    }
}