<?php

/**
 * PreferenciaturisticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreferenciaturisticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreferenciaturisticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Preferenciaturistica');
    }
}