<?php

/**
 * PreoperatorioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreoperatorioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreoperatorioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Preoperatorio');
    }

    public function obtenerTratamientos($codigo_tratamiento)
    {
        $query = $this->createQuery('p')->where('preo_tra_codigo=' . $codigo_tratamiento);
        return $query->execute();
    }
}