<?php

/**
 * PreoperatorioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreoperatorioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreoperatorioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Preoperatorio');
    }
}