<?php

/**
 * ProcedimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProcedimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProcedimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Procedimiento');
    }
}