<?php

/**
 * ReservavueloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservavueloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReservavueloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reservavuelo');
    }
}