<?php

/**
 * TransporteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransporteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TransporteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Transporte');
    }
}