<?php

/**
 * Tratamiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pitetravel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tratamiento extends BaseTratamiento
{
    public function delete(Doctrine_Connection $conn = null) {
        if(0 < sizeof($this->Dietapaciente))
            $this->Dietapaciente->delete();

        if(0 < sizeof($this->Logistica))
            $this->Logistica->delete();

        if(0 < sizeof($this->Postoperatorio))
            $this->Postoperatorio->delete();

        if(0 < sizeof($this->Preoperatorio))
            $this->Preoperatorio->delete();

        if(0 < sizeof($this->Procedimiento))
            $this->Procedimiento->delete();

        if(0 < sizeof($this->Reservahotel))
            $this->Reservahotel->delete();

        if(0 < sizeof($this->Reservavuelo))
            $this->Reservavuelo->delete();


        parent::delete($conn);
    }
}
