<?php

/**
 * UsuariosagenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuariosagenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuariosagenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usuariosagencia');
    }

    public function obtenerPorUsuario($id_usuario)
    {
        $query = $this->createQuery()->where('uag_sfu_id = ' . $id_usuario);
        return $query->execute()->getFirst();
    }

    public function obtenerAgenciaUsuario($id_usuario)
    {
        $result = $this->obtenerPorUsuario($id_usuario);
        return $result ? $result->Agencia : $result;
    }
}