generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Hotel
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          hotel
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: Hoteles en el sistema
        display: [=hot_nombre, hot_telefono, hot_email]
        fields:
          hot_nombre: {label: Nombre del Hotel}
          hot_telefono: {label: Tel&eacute;fono}
          hot_email: {label: Correo Electr&oacute;nico}
      filter:
        class: false
      form:    ~
      edit:
        title: Actualizando la informaci&oacute;n para %%hot_nombre%%
      new:
        title: Ingresando un nuevo Hotel
